spin_version = "1"
authors = ["a"]
description = "A hello world application that serves content from a Rust program"
name = "spin-wagi-hello"
trigger = { type = "http", base = "/jumpthequeue/services/" }
version = "1.0.0"

[[component]]
id = "router"
source = "target/wasm32-wasi/release/rust.wasm"
[component.trigger]
route = "/rest/..."
executor =  { type = "spin" }
[component.build]
command = "cargo build --target wasm32-wasi --release --manifest-path Cargo.toml"
