version: '3'
services:
  server:
    image: postgrest/postgrest:v9.0.1
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://jtq_user:admin@jtq_postgres:5432/jtq_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: jtq_user
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - jtq_postgres
  jtq_postgres:
    image: postgres:14.2
    container_name: jtq_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
  # visual overview of the API
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/