use crate::api::common::dataaccess::api::new_entity::NewEntity;
use crate::api::common::logic::api::eto::EntityETO;

/*
    This trait defines the structure of an Entity. The from_insert method is only needed
    in those entities that have autogenerated IDs, that will need an insertable variant
*/
pub trait Entity<ID, NE, ETO>: Into<ETO>
    where 
        NE: NewEntity<ETO>, 
        ETO: EntityETO 
{
    fn from_insert(id: ID, new_entity: NE) -> Self;
}
