version: '3.7'

services:
  jtq_postgres:
    container_name: jtq-postgres
    image: postgres:14.2
    env_file:
      - ../postgresql/config.env
    volumes:
      - ../postgresql/postgres/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - vnet
  # jtq_rust:
  #   # build: ../rust
  #   image: max/jtq-rust-simple
  #   depends_on:
  #       - jtq_postgres
  #   container_name: jtq-rust
  #   environment:
  #     - DATABASE_URL=postgres://jtq_user:admin@jtq-postgres/jtq_db
  #     - BIND_URL=0.0.0.0:8081
  #     - BASE_REST_URL=jumpthequeue/services/rest/
  #   ports:
  #     - "8082:8081"
  #   restart: on-failure
  #   networks:
  #     - vnet
  jtqq:
    image: max/jtqq
    depends_on:
        - jtq_postgres
    ports:
      - "8082:8081"
    environment:
      - DB_HOST=jtq-postgres
      - DB_NAME=jtq_db
      - DB_USER=jtq_user
      - DB_PASS=admin
    restart: on-failure
    networks:
      - vnet
  # jtqj_native:
  #   image: docker.io/library/jtqj-native:1.0.0-SNAPSHOT
  #   depends_on:
  #       - jtq_postgres
  #   ports:
  #     - "8082:8081"
  #   environment:
  #     - DB_HOST=jtq-postgres
  #     - DB_NAME=jtq_db
  #     - DB_USER=jtq_user
  #     - DB_PASS=admin
  #   restart: on-failure
  #   networks:
  #     - vnet

networks:
  vnet: