version: '3.8'
services:
  jtq_postgres:
    container_name: jtq-postgres
    image: postgres:14.2
    env_file:
      - ../postgresql/config.env
    volumes:
      - ../postgresql/postgres/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - vnet
  jtq_rust:
    depends_on:
        - postgres
    container_name: jtq-java
    image: jtq-java
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jtq-postgres/jtq_db
      - SPRING_DATASOURCE_USERNAME=jtq_user
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8081:8081"
    restart: on-failure
    networks:
      - vnet
networks:
  vnet: