version: '2.1'
services:
  atmo-server:
    image: suborbital/atmo:latest
    container_name: atmo_server
    entrypoint: atmo
    environment:
      - ATMO_HTTP_PORT=8081
    ports:
      - 8081:8081
    depends_on:
      jtq_postgres:
        condition: service_healthy
    volumes:
      - ./rust_atmos:/home/atmo
    networks: 
      - vnet

  jtq_postgres:
    container_name: jtq_postgres_intern
    image: postgres:14.2
    env_file:
      - ../postgresql/config.env
    volumes:
      - ../postgresql/postgres/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    ports:
      - 5432:5432
    networks: 
      - vnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

networks: 
  vnet:

