version: '3.8'
services:
  jtq_postgres:
    container_name: jtq-postgres
    image: postgres:14.2
    env_file:
      - ../postgresql/config.env
    volumes:
      - ../postgresql/postgres/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - vnet
  jtq_rust:
    build: .
    depends_on:
        - postgres
    container_name: jtq-rust
    environment:
      - DATABASE_URL=postgres://jtq_user:admin@jtq-postgres/jtq_db
      - BIND_URL=0.0.0.0:8081
      - BASE_REST_URL=jumpthequeue/services/rest/
    ports:
      - "8081:8081"
    restart: on-failure
    networks:
      - vnet
networks:
  vnet: