version: '3.8'
services:
  jtq_postgres:
    container_name: jtq_postgres_intern
    image: postgres:14.2
    env_file:
      - ../postgresql/config.env
    volumes:
      - ../postgresql/postgres/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - vnet
  
  jtq_node:
    depends_on:
        - jtq_postgres
    container_name: jtq_node
    image: node:17
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - DB_HOST=jtq_postgres_intern
      - DB_PORT=5432
      - DB_NAME=jtq_db
      - DB_USER=jtq_user
      - DB_PASSWORD=admin
      - BASE_REST_URL=jumpthequeue/services/rest
      - EXECUTION=cluster
    ports:
      - "8081:8081"
    command: "npm run start"
    restart: on-failure
    networks:
      - vnet

networks:
  vnet: