host: "localhost"
port: 8081
use_https: false
base_path: "/jumpthequeue/services/rest"
users: 5
goose_log: "goose.log"
user_creation_rate: "1"
run_time: "10"
report_file: "report.html"
request_log: "request.log"
request_body: true
error_log: "error.log"
debug_log: "debug.log"
max_request_second: 0
no_reset_metrics: true

benchmarks:
  -
    name: "Benchmark normal entities JTQ"
    request_groups:
      -
        requests:
          -
            method: GET
            path: "/visitormanagement/v1/visitor/1/"
          -
            method: POST
            path: "/visitormanagement/v1/visitor/"
            content_type: "application/json"
            body: |
              {
                "username": "user@mail.com",
                "name": "pepe",
                "phoneNumber": "+34623456789",
                "password": "paco",
                "acceptedTerms": true,
                "acceptedCommercial": false
              }
            should_delete: true
            body_field_for_delete: "id"
            delete_end_slash: true
          -
            method: POST
            path: "/visitormanagement/v1/visitor/search/"
            content_type: "application/json"
            body: |
              {
                "pageable": {
                  "pageSize": 10,
                  "pageNumber": 0
                }
              }
      -
        requests:
          -
            method: GET
            path: "/queuemanagement/v1/queue/1/"
          -
            method: POST
            path: "/queuemanagement/v1/queue/"
            content_type: "application/json"
            body: |
              {
                "modificationCounter": 1,
                "name": "Name",
                "logo": "C:/logos/Day1Logo.png",
                "currentNumber": "Q001",
                "minAttentionTime": "1969-12-31T23:01:00.000",
                "active": true 
              }
            should_delete: true
            body_field_for_delete: "id"
            delete_end_slash: true
          -
            method: POST
            path: "/queuemanagement/v1/queue/search/"
            content_type: "application/json"
            body: |
              {
                "pageable": {
                  "pageSize": 10,
                  "pageNumber": 0
                }
              }
