version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.2
    env_file:
      - extras1.env
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    restart: unless-stopped